blog/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time    :2020/5/4 18:28
# @Author  :zhouyuyao
# @File    :urls.py

from django.contrib import admin
from django.urls import path, include, re_path

from . import views



urlpatterns = [
    path('', views.index),
    # artical_id 需和 views 中 artical_page 参数保持一致
    path('artical/<int:artical_id>', views.artical_page,name='artical_page'),
    path('edit/<int:artical_id>', views.edit_page,name='edit_page'),
    path('edit/action/', views.edit_action,name='edit_action'),

]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

import blog.views as bv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', bv.index),
    path('blog/', include(("blog.urls", "blog"), namespace="blog")),
]

blog/models.py
from django.db import models

# Create your models here.


class Artical(models.Model):
    title=models.CharField(max_length=32,default="Title")
    content=models.TextField(null=True)
    pub_date=models.DateTimeField(auto_now=True)
    # python manage.py shell 可以测试未知的方法，Artical.objects.all().values()
    def __str__(self):
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from blog import models


def index(request):
    # return HttpResponse("Hello blog.")
    articals = models.Artical.objects.all()
    return render(request, "index.html", {'articals': articals})


def artical_page(request, artical_id):
    artical = models.Artical.objects.get(pk=artical_id)
    return render(request, "blog/artical_page.html", {'artical': artical})


def edit_page(request, artical_id):
    # 在新建文章中传 0，在修改文章中传artical_id
    if str(artical_id) == '0':
        return render(request, "blog/edit_page.html")
    artical = models.Artical.objects.get(pk=artical_id)
    return render(request, "blog/edit_page.html", {'artical': artical})


def edit_action(request):
    artical_id = request.POST.get('artical_id','0')
    # print(artical_id) 从 edit_page 接收过来的值
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')

    if artical_id == '0':
        models.Artical.objects.create(title=title, content=content)
        articals = models.Artical.objects.all()
        return render(request, "index.html", {"articals": articals})
    artical = models.Artical.objects.get(pk=artical_id)
    artical.title = title
    artical.content = content
    artical.save()
    # artical.update()
    # 修改完成后跳转至文章页面
    return render(request, "blog/artical_page.html", {'artical': artical})

blog2/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/artical_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Artical Page</title>
</head>
<body>
<h1>
    {{artical.title}}
</h1>
<br/>
<h3>
    {{artical.content}}
</h3>
<br/>
<br/>
<a href="{% url 'blog:edit_page' artical.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    <!--    post请求时需要设置 csrf_token 防范出现验证错误 即跨站请求-->
    {% csrf_token %}
<!--                              {{ artical.id | default:'0' }}       采用过滤器-->
    <input type="hidden" name="artical_id" value="{{ artical.id | default:'0' }}"/>
    <label>文章标题
        <input type="text" name="title" value="{{ artical.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{ artical.content }}"/>
    </label>
    <br/>


<!--    {% if artical %}-->
<!--&lt;!&ndash;    name="artical_id" 可以渲染到 views，通过request.POST.get到该值 &ndash;&gt;-->
<!--    <input type="hidden" name="artical_id" value="{{artical.id}}"/>-->
<!--    <label>文章标题-->
<!--        <input type="text" name="title" value="{{artical.title}}"/>-->
<!--    </label>-->
<!--    <br/>-->
<!--    <label>文章内容-->
<!--        <input type="text" name="content" value="{{artical.content}}"/>-->
<!--    </label>-->
<!--    <br/>-->
<!--    {% else %}-->
<!--    <input type="hidden" name="artical_id" value="0"/>-->
<!--    <label>文章标题-->
<!--        <input type="text" name="title"/>-->
<!--    </label>-->
<!--    <br/>-->
<!--    <label>文章内容-->
<!--        <input type="text" name="content""/>-->
<!--    </label>-->
<!--    <br/>-->
<!--    {% endif %}-->


    <input type="submit" value="提交">
</form>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello myblog</title>
    <h1>“对于一只盲目航行的船来说，所有的风都是逆风”。</h1>
    <h1>{{hello}}</h1>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
<h2>
{% for artical in articals %}
    <a href="{% url 'blog:artical_page' artical.id %}">{{ artical.title }}</a>
    <br/>
{% endfor %}
</h2>
</body>
</html>